#!/usr/bin/env bash

# Set ip address 
if [ ! -z "$IPV6ADDR" ]; then
	echo  $IPV6ADDR
	ip -6 addr add "$IPV6ADDR" dev eth0
fi
sleep 2

# Set gateway
if [ ! -z "$IPV6GW" ]; then
	echo $IPV6GW
	ip -6 route add  default via "$IPV6GW" dev eth0
fi

# Copy supervisord conf
cp ./config/supervisord.conf /etc/supervisor/supervisord.conf

# Fire up Softether!
supervisord