id: softether
kind: Pod
apiVersion: v1beta1
desiredState: 
 manifest: 
  version: v1beta1
  id: softether
  containers: 
  - name: softether
    image: "va4man/softether"
    ports:
      - name: sstp
        containerPort: 443
        hostPort: 443
      - name: ssl
        containerPort: 992
        hostPort: 992
      - name: admin
        containerPort: 5555
        hostPort: 5555
    env:
      - name: GIT_URL
        value: https://github.com/Vachman/softether.git
    volumeMounts:
      - name: softether-data
        mountPath: /usr/local/vpnserver 
  volumes:
    - name: softether-data      
labels: 
 name: softether
 environment: production